Repository CAUCSE/CAUSW_frontend_V2, pull requests merged in 2024-10, with the labels that each got.

#37 [FEAT] 타입 에러 해결 및 신청서 개별 결과 페이지 추가
  src/app/(causw)/board/[boardId]/[postId]/[formId]/page.tsx
  src/app/(causw)/board/[boardId]/[postId]/formInfo/[formId]/page.tsx
  src/app/(causw)/board/[boardId]/[postId]/page.tsx
  src/app/(causw)/board/[boardId]/create/page.tsx
  src/app/(causw)/board/[boardId]/page.tsx
  src/app/(causw)/board/[boardId]/search/page.tsx
  src/app/(causw)/board/create/page.tsx
  src/app/(causw)/board/page.tsx
  src/app/(causw)/circle/[id]/board/page.tsx
  src/entities/board/form/Option.tsx
  src/entities/board/form/Question.tsx
  src/entities/board/main/Board.tsx
  src/entities/board/main/CustomBoard.tsx
  src/entities/board/main/DefaultBoard.tsx
  src/entities/board/main/EmptyContent.tsx
  src/entities/board/main/MainBoard.tsx
  src/entities/board/postList/PostList.tsx
  src/entities/board/postList/PostListHeader.tsx
  src/entities/board/postList/PostListUtil.ts
  src/entities/index.ts
  src/shared/@types/board.d.ts
  src/shared/@types/post.d.ts
  src/shared/@types/user.d.ts
  src/shared/hooks/services/BoardRscService.tsx
  src/shared/hooks/services/MainBoardRscService.tsx
  src/shared/hooks/services/PostRscService.tsx
  src/shared/hooks/stores/post/usePostListStore.ts
  src/shared/index.ts
  src/shared/ui/previousButton.tsx
Labels: feat, fix

#36 [FEAT] 회원가입 & 유저 개인 설정 & 동아리원 상세 페이지 (#18)
  src/app/(causw)/setting/management/circle/[id]/[state]/detail/[userId]/page.tsx
  src/app/(causw)/setting/management/payer/[councilFeeId]/page.tsx
  src/app/(causw)/setting/management/payer/page.tsx
  src/app/(causw)/setting/page.tsx
  src/app/(causw)/setting/personal-info/page.tsx
  src/app/auth/authorization/page.tsx
  src/app/auth/authorization/submitacademicrecords/page.tsx
  src/app/auth/authorization/submitadmissionsapplication/page.tsx
  src/entities/application/AcademicRecordInput.tsx
  src/entities/application/AdmissionApplicationPage.tsx
  src/entities/home/setting/BannerCard.tsx
  src/entities/home/setting/EventEditModal.tsx
  src/entities/home/setting/NewCalendarModal.tsx
  src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
  src/entities/home/setting/management/CircleManagementDetailButtons.tsx
  src/entities/home/setting/management/ManagementDetailButtons.tsx
  src/entities/home/setting/management/index.ts
  src/entities/layout/ProfileImage.tsx
  src/shared/@types/user.d.ts
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/services/CircleService.tsx
  src/shared/hooks/services/HomeRscService.tsx
  src/shared/hooks/services/SettingRscService.tsx
  src/shared/hooks/services/UserCouncilFeeService.tsx
  src/shared/hooks/services/UserRscService.tsx
  src/shared/hooks/services/UserService.tsx
  src/shared/hooks/stores/useUserStore.ts
  src/widget/AdmissionManagementDetail.tsx
  src/widget/CircleMemberManagement.tsx
  src/widget/CircleMemberManagementDetail.tsx
  src/widget/ManagementDetailInfoTable.tsx
  src/widget/index.ts
Labels: feat

#54 [FIX]: 회원가입 후 재학 증빙서류 제출 페이지에서 발생하는 오류 수정 ( # 36 )
  src/entities/application/AcademicRecordInput.tsx
Labels: fix

#55 [Fix #21] 개발계 배포 후 추가 수정사항 및 버그 수정 사항 반영
  src/app/(causw)/board/[boardId]/[postId]/formInfo/[formId]/page.tsx
  src/app/(causw)/board/[boardId]/page.tsx
  src/entities/board/postList/PostList.tsx
Labels: fix

#57 [FIX] Circle Application Error
  src/app/(causw)/setting/management/circle/[id]/[state]/[userId]/page.tsx
  src/shared/@types/circle.d.ts
  src/shared/hooks/services/CircleRscSevice.tsx
  src/shared/hooks/services/CircleService.tsx
  src/widget/Management.tsx
Labels: fix

#60 [FEAT] Home & Sign In & Sign Up Page Design Upgrade
  src/app/(causw)/home/page.tsx
  src/app/(causw)/layout.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/entities/background/ImageBackground.tsx
  src/entities/home/Banner.tsx
  src/entities/home/Calendar.tsx
  src/entities/home/card/HomeCard.tsx
  src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
  src/entities/input/FormInput.tsx
  src/entities/layout/NavigationBar.tsx
  src/shared/@types/home.d.ts
  src/shared/hooks/services/AuthRscService.tsx
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/services/HomeRscService.tsx
  src/shared/hooks/services/UserService.tsx
  src/widget/SideBar.tsx
Labels: design, feat

#63 [fix/#62]: 게시판 게시글 제목에만 a태그가 적용되는 문제 해결
  src/entities/board/main/Board.tsx
Labels: fix

#65 [Feat/#64] 사진이 있는 게시글의 경우, 게시글 목록에서 첨부된 사진이 썸네일로 설정되게 기능 추가
  src/entities/board/postList/PostList.tsx
  src/shared/@types/post.d.ts
Labels: feat

#66 [Feat] 유저 상세 페이지 및 버튼 구현
  src/app/(causw)/setting/management/user/[state]/[admissionId]/page.tsx
  src/app/(causw)/setting/management/user/[state]/page.tsx
  src/app/(causw)/setting/page.tsx
  src/app/(causw)/setting/useterms/page.tsx
  src/app/auth/authorization/page.tsx
  src/app/auth/signup/page.tsx
  src/entities/application/AdmissionApplicationPage.tsx
  src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
  src/entities/home/setting/management/ManagementDetailButtons.tsx
  src/entities/home/setting/management/WarningModal.tsx
  src/entities/home/useTerms.tsx
  src/shared/@types/setting.d.ts
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/services/SettingRscService.tsx
  src/shared/hooks/services/UserRscService.tsx
  src/shared/index.ts
  src/shared/ui/Button.tsx
  src/shared/ui/noButtonModal.tsx
  src/widget/AdmissionManagementDetail.tsx
  src/widget/CircleMemberManagementDetail.tsx
  src/widget/Management.tsx
  src/widget/ManagementDetailInfoTable.tsx
Labels: chore

#78 [FIX] Deploy Routing Error
  README.md
  src/app/(causw)/home/page.tsx
  src/app/error.tsx
Labels: fix

#80 [HOTFIX] Signup Process Error
  next.config.mjs
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/shared/hooks/services/AuthService.tsx
Labels: hotfix
