Repository CAUCSE/CAUSW_frontend_V2, pull requests merged in 2025-03, with the labels that each got.

#127 [CHORE] 회원가입시 발생하는 에러 수정
  src/app/auth/signup/page.tsx
  src/shared/@types/user.d.ts
Labels: chore, fix

#133 [#132] 아이디, 비밀번호 찾기 시 API request body와 폼 전화번호 형식이 다른 문제 해결
  src/app/auth/findemail/error.tsx
  src/app/auth/findemail/layout.tsx
  src/app/auth/findemail/page.tsx
  src/app/auth/findpassword/error.tsx
  src/app/auth/findpassword/layout.tsx
  src/app/auth/findpassword/page.tsx
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/stores/useFindAccountStore.ts
  src/shared/index.ts
Labels: fix

#136 [FIX] 유저 관리 페이지 페이지네이션 적용 안되는 문제
  src/app/(causw)/setting/management/user/[state]/[admissionId]/layout.tsx
  src/app/(causw)/setting/management/user/[state]/[admissionId]/page.tsx
  src/app/(causw)/setting/management/user/[state]/page.tsx
  src/app/(causw)/setting/management/user/layout.tsx
  src/shared/@types/setting.d.ts
  src/shared/@types/user.d.ts
  src/shared/hooks/services/SettingRscService.tsx
  src/shared/index.ts
  src/shared/ui/PaginationButtons.tsx
  src/widget/Management.tsx
Labels: feat, fix

#138 [FIX] 유저 정보 상세보기 페이지에서 재학증빙 서류 이미지 에러 해결
  src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
  src/shared/hooks/services/UserRscService.tsx
  src/widget/AdmissionManagementDetail.tsx
  src/widget/Management.tsx
  src/widget/ManagementDetailInfoTable.tsx
Labels: fix

#139 [DEPLOY] V2.2.4
  src/app/(causw)/setting/management/user/[state]/[admissionId]/layout.tsx
  src/app/(causw)/setting/management/user/[state]/[admissionId]/page.tsx
  src/app/(causw)/setting/management/user/[state]/page.tsx
  src/app/(causw)/setting/management/user/layout.tsx
  src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
  src/shared/@types/setting.d.ts
  src/shared/@types/user.d.ts
  src/shared/hooks/services/SettingRscService.tsx
  src/shared/hooks/services/UserRscService.tsx
  src/shared/index.ts
  src/shared/ui/PaginationButtons.tsx
  src/widget/AdmissionManagementDetail.tsx
  src/widget/Management.tsx
  src/widget/ManagementDetailInfoTable.tsx
Labels: chore, fix

#141 140 fix 게시판 이미지 관련 스타일 수정 및 부가 기능 추가
  src/app/auth/findpassword/page.tsx
  src/entities/board/post/PostCard.tsx
  src/widget/board/BoardList.tsx
Labels: chore, design, feat

#142 [DEPLOY] V2.2.5
  src/app/auth/findpassword/page.tsx
  src/entities/board/post/PostCard.tsx
  src/widget/board/BoardList.tsx
Labels: chore, design, feat

#144 [CHORE] 이미지 뷰 사이즈 관련 처리
  src/app/(causw)/setting/management/attendance/detail/waiting/[id]/page.tsx
  src/app/auth/findemail/page.tsx
  src/app/auth/findpassword/page.tsx
  src/entities/board/post/PostCard.tsx
  src/entities/locker/LockerSelect.tsx
  src/shared/hooks/lockers/useSelectLocker.ts
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/stores/useFindAccountStore.ts
  src/shared/ui/ImageList.tsx
  src/shared/ui/ImageViewer.tsx
  src/widget/locker/LockerSelectGrid.tsx
Labels: chore, design

#145 [DEPLOY] V2.2.6
  src/app/(causw)/setting/management/attendance/detail/waiting/[id]/page.tsx
  src/app/auth/findemail/page.tsx
  src/app/auth/findpassword/page.tsx
  src/entities/board/post/PostCard.tsx
  src/entities/locker/LockerSelect.tsx
  src/shared/hooks/lockers/useSelectLocker.ts
  src/shared/hooks/services/AuthService.tsx
  src/shared/hooks/stores/useFindAccountStore.ts
  src/shared/ui/ImageList.tsx
  src/shared/ui/ImageViewer.tsx
  src/widget/locker/LockerSelectGrid.tsx
Labels: chore, design

#150 [FEAT] Layout & Sign In & Payer Page
  src/app/(causw)/setting/management/payer/add/[userId]/page.tsx
  src/app/(causw)/setting/management/payer/add/layout.tsx
  src/app/error.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/entities/background/VideoBackground.tsx
  src/entities/input/FormInput.tsx
  src/entities/layout/NavigationBar.tsx
  src/shared/hooks/services/SettingRscService.tsx
Labels: chore, design, fix

#148 [Fix/#147/banner error fix] 배너 최대 등록 개수 초과 시 에러 메세지 미출력 문제 해결
  src/app/(causw)/setting/home/@modal/(.)event/layout.tsx
  src/app/(causw)/setting/home/event/error.tsx
  src/app/(causw)/setting/home/event/layout.tsx
  src/app/(causw)/setting/home/event/page.tsx
  src/entities/home/setting/BannerCard.tsx
  src/entities/home/setting/EventEditModal.tsx
  src/shared/configs/query-key/eventQueryKey.ts
  src/shared/hooks/events/useEditEvent.ts
  src/shared/hooks/services/HomeRscService.tsx
  src/shared/hooks/services/HomeService.ts
  src/shared/hooks/stores/event/useEventStore.ts
  src/shared/index.ts
Labels: chore, fix

#152 [fix/#147/setting-my-page] 설정-내가 쓴 글, 댓글, 찜한 글 기본 썸네일 삭제 및 무한스크롤 기능 추가
  src/app/(causw)/board/[boardId]/create/page.tsx
  src/app/(causw)/setting/my/comments/error.tsx
  src/app/(causw)/setting/my/comments/page.tsx
  src/app/(causw)/setting/my/favorite/error.tsx
  src/app/(causw)/setting/my/favorite/page.tsx
  src/app/(causw)/setting/my/layout.tsx
  src/app/(causw)/setting/my/posts/error.tsx
  src/app/(causw)/setting/my/posts/page.tsx
  src/entities/board/post/create/CreatePostFooter.tsx
  src/entities/board/post/create/PostForm.tsx
  src/entities/board/postList/PostItem.tsx
  src/shared/@types/form.d.ts
  src/shared/@types/pagination.d.ts
  src/shared/@types/post.d.ts
  src/shared/@types/user.d.ts
  src/shared/configs/query-key/index.ts
  src/shared/configs/query-key/settingQueryKey.ts
  src/shared/hooks/posts/usePostInteraction.ts
  src/shared/hooks/services/SettingService.tsx
  src/shared/index.ts
  src/widget/index.ts
  src/widget/post/apply/ApplyCreationForm.tsx
  src/widget/setting/MyPageHeader.tsx
  src/widget/setting/MyPostList.tsx
  src/widget/setting/index.ts
Labels: design, fix

#154 [DEPLOY] V2.3.1
  src/_deprecated/test/page.tsx
  src/app/auth/signin/page.tsx
Labels: hotfix

#157 Fix/#147
  next.config.mjs
  package-lock.json
  package.json
  public/icons/add_icon.svg
  public/icons/delete_icon.svg
  public/icons/dropdown_icon.svg
  public/icons/image_icon.svg
  public/icons/link_icon.svg
  src/app/(causw)/setting/home/@modal/(.)calendar/new/page.tsx
  src/app/(causw)/setting/home/@modal/(.)event/[id]/page.tsx
  src/app/(causw)/setting/home/@modal/(.)event/layout.tsx
  src/app/(causw)/setting/home/@modal/(.)event/new/page.tsx
  src/app/(causw)/setting/home/@modal/default.tsx
  src/app/(causw)/setting/home/banner/error.tsx
  src/app/(causw)/setting/home/banner/page.tsx
  src/app/(causw)/setting/home/calendar/error.tsx
  src/app/(causw)/setting/home/calendar/page.tsx
  src/app/(causw)/setting/home/event/layout.tsx
  src/app/(causw)/setting/home/event/page.tsx
  src/app/(causw)/setting/home/layout.tsx
  src/app/(causw)/setting/page.tsx
  src/entities/banner/BannerCard.tsx
  src/entities/banner/BannerDeleteModal.tsx
  src/entities/banner/BannerEditModal.tsx
  src/entities/calendar/CalendarAddModal.tsx
  src/entities/calendar/CalendarCard.tsx
  src/entities/calendar/CalendarDeleteModal.tsx
  src/entities/home/index.ts
  src/entities/home/setting/BannerCard.tsx
  src/entities/home/setting/EventEditModal.tsx
  src/entities/home/setting/NewCalendarModal.tsx
  src/entities/index.ts
  src/shared/@types/banner.d.ts
  src/shared/@types/calendar.d.ts
  src/shared/configs/query-key/bannerQueryKey.ts
  src/shared/configs/query-key/calendarQueryKey.ts
  src/shared/configs/query-key/index.ts
  src/shared/hooks/banner/useEditBanner.ts
  src/shared/hooks/calendar/useAddCalendarModal.ts
  src/shared/hooks/calendar/useDeleteCalendarModal.ts
  src/shared/hooks/events/useEditEvent.ts
  src/shared/hooks/services/BannerService.tsx
  src/shared/hooks/services/CalendarService.tsx
  src/shared/hooks/services/HomeRscService.tsx
  src/shared/hooks/stores/banner/useBannerStore.ts
  src/shared/hooks/stores/calendar/useCalendarStore.ts
  src/shared/hooks/stores/event/useEventStore.ts
  src/shared/index.ts
  src/shared/ui/CustomSelect.tsx
  src/shared/ui/EmptyComponent.tsx
  src/shared/ui/PortalModal.tsx
  src/widget/banner/BannerList.tsx
  src/widget/banner/BannerSettingHeader.tsx
  src/widget/calendar/CalendarList.tsx
  src/widget/calendar/CalendarListHeader.tsx
  src/widget/index.ts
  tsconfig.json
Labels: fix, refactor

#168 [HOTFIX/#167] 캘린더 페이지가 빈화면으로 렌더링되는 문제 해결
  src/app/(causw)/setting/home/calendar/page.tsx
Labels: hotfix
