Repository CAUCSE/CAUSW_frontend_V2, pull requests merged in 2025-07, with the labels that each got.

#202 [DEPLOY] Update assetlinks.json
  public/.well-known/assetlinks.json
Labels: docs, hotfix

#204 [FEAT/#203] 게시글 컨텐츠 HTML 렌더링 기능 추가
  package-lock.json
  package.json
  src/fsd_entities/post/ui/PostCard/PostCard.tsx
  src/fsd_entities/post/ui/PostCard/PostCardContent.tsx
  src/fsd_entities/post/ui/PostDetailContent/PostDetailContent.tsx
Labels: feat, dependency

#209 [FIX/#208] 게시글 관련 QA 반영
  next.config.mjs
  package-lock.json
  package.json
  public/.well-known/assetlinks.json
  src/app/(causw)/board/[boardId]/create/page.tsx
  src/fsd_entities/post/ui/PostCard/PostCardContent.tsx
  src/fsd_entities/post/ui/PostDetailContent/PostDetailContent.tsx
  src/fsd_shared/model/index.ts
  src/fsd_shared/model/sanitizeHtml.ts
  src/fsd_widgets/form/ui/FormCreationForm/FormCreationForm.tsx
  src/fsd_widgets/post/ui/PostCreationFormButtonGrorup/PostCreationFormButtonGroup.tsx
Labels: fix

#216 [FEAT/#214] Gemini Code Assist 추가 및 리뷰 스타일 설정
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: feat

#221 [FIX] 탭 UI 반응형 레이아웃 깨짐 현상 수정 #220
  src/fsd_entities/notification/model/useNotificationTabParam.ts
  src/fsd_widgets/ceremony/ui/CeremonyTabs.tsx
  src/fsd_widgets/notification/ui/NotificationTabs.tsx
  src/shadcn/components/ui/tabs.tsx
Labels: fix

#225 [STYLE] 로그인 화면 디자인 리뉴얼
  package-lock.json
  package.json
  public/images/chungang_logo.svg
  src/app/auth/signin/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/entities/layout/ErrorMessage.tsx
  src/fsd_entities/auth/ui/SignInInput.tsx
  src/fsd_entities/auth/ui/SignInSubmitButton.tsx
  src/fsd_widgets/auth/ui/SignInFooter.tsx
  src/shadcn/components/ui/index.ts
  src/shadcn/components/ui/switch.tsx
  tailwind.config.js
Labels: design, feat

#226 [Feat] 크자회 홈&설정 화면 UI 구현
  .gemini/config.yaml
  public/homeIcons/경조사.svg
  public/homeIcons/동문수첩.svg
  public/homeIcons/크자회_공지_게시판.svg
  public/homeIcons/크자회_소통_게시판.svg
  public/icons/message_icon.svg
  src/app/(causw)/home/ClientGate.tsx
  src/app/(causw)/home/ClientGraduatePage.tsx
  src/app/(causw)/home/ClientPage.tsx
  src/app/(causw)/home/page.tsx
  src/app/(causw)/setting/page.tsx
  src/app/auth/signin/page.tsx
  src/fsd_entities/notification/api/get.ts
  src/fsd_entities/user/model/stores/useMyInfoStore.ts
  src/fsd_shared/@types/user.d.ts
  src/widget/SideBar.tsx
Labels: feat

#222 [FEAT] 크자회 채팅 ui
  public/icons/add-gray.svg
  public/icons/pink_send_icon.svg
  public/icons/send.svg
  public/images/puang_profile.svg
  src/app/(causw)/chat/[chatId]/page.tsx
  src/app/(causw)/chat/page.tsx
  src/fsd_entities/auth/model/useAcademicRecordForm.ts
  src/fsd_entities/chat/MessageItem.tsx
  src/fsd_shared/@types/chat.ts
  src/fsd_shared/hooks/index.ts
  src/fsd_shared/hooks/useMoreBtnClick.ts
  src/fsd_shared/ui/DateLabel.tsx
  src/fsd_shared/ui/FullLine.tsx
  src/fsd_shared/ui/index.ts
  src/fsd_widgets/chat/index.ts
  src/fsd_widgets/chat/ui/ChatList.tsx
  src/fsd_widgets/chat/ui/ChatListItem.tsx
  src/fsd_widgets/chat/ui/ChatRoom.tsx
  src/fsd_widgets/chat/ui/index.ts
  src/shared/hooks/auth/useSubmitApplication.ts
  src/widget/SideBar.tsx
  src/widget/index.ts
Labels: feat
