Repository CAUCSE/CAUSW_frontend_V2, pull requests merged in 2025-08, with the labels that each got.

#232 [FEAT] 크자회 전용 페이지 및 게시판 UI
  public/icons/alumni_notice.svg
  public/icons/cssaa_notice.svg
  public/icons/cssaa_post.svg
  public/icons/deliver_notice.svg
  public/icons/error_notice.svg
  public/icons/free_post.svg
  public/icons/service_notice.svg
  public/icons/sw_notice.svg
  src/app/(causw)/home/ClientGate.tsx
  src/app/(causw)/home/ClientGraduatePage.tsx
  src/app/(causw)/home/ClientPage.tsx
  src/app/(causw)/home/page.tsx
  src/app/(causw)/setting/page.tsx
  src/fsd_entities/board/model/hooks/fetchBoardList.ts
  src/fsd_entities/board/ui/BoardList/Board.tsx
  src/fsd_entities/board/ui/BoardList/EmptyBoard.tsx
  src/fsd_entities/notification/api/get.ts
  src/fsd_entities/post/ui/PostCard/PostCardStatusBar.tsx
  src/fsd_shared/@types/board.d.ts
  src/fsd_widgets/board/ui/BoardList/BoardList.tsx
  src/fsd_widgets/board/ui/BoardList/BoardListClient.tsx
  src/fsd_widgets/board/ui/BoardList/CustomBoard.tsx
  src/fsd_widgets/board/ui/BoardList/DefaultNoticeBoard.tsx
  src/fsd_widgets/notification/ui/NotificationWidget.tsx
  src/fsd_widgets/pageLayout/ui/SideBar.tsx
  src/shared/hooks/services/HomeRscService.tsx
Labels: feat

#241 [CHORE] 사물함 설명 줄바꿈 방지
  src/fsd_widgets/locker/ui/LockerSelectionMobileManual.tsx
Labels: chore, design

#243 [FIX] QA 주요 기능(게시판/경조사/알림/UI) 오류 및 개선
  src/fsd_entities/board/api/post.ts
  src/fsd_entities/board/index.ts
  src/fsd_entities/board/model/hooks/index.ts
  src/fsd_entities/board/model/hooks/useSelectRole.ts
  src/fsd_entities/board/model/queries/useCreateNoticeBoard.ts
  src/fsd_entities/board/model/stores/boardCreationSlice.ts
  src/fsd_entities/board/ui/BoardCreationForm/AllowAlumniToggle.tsx
  src/fsd_entities/board/ui/BoardCreationForm/BoardDetailForm.tsx
  src/fsd_entities/board/ui/BoardCreationForm/RoleSelectSection.tsx
  src/fsd_entities/board/ui/BoardCreationForm/index.ts
  src/fsd_entities/board/ui/BoardList/Board.tsx
  src/fsd_entities/comment/ui/CommentInfoSection/CommentInfoSection.tsx
  src/fsd_entities/post/ui/PostWriterProfileImage/PostWriteProfileImage.tsx
  src/fsd_entities/user/ui/ManageSettings/ManagementPanel.tsx
  src/fsd_shared/@types/ceremony.ts
  src/fsd_shared/configs/constants/index.ts
  src/fsd_shared/configs/constants/roles.ts
  src/fsd_shared/model/format.ts
  src/fsd_shared/model/index.ts
  src/fsd_widgets/board/ui/BoardCreationForm/BoardCreationForm.tsx
  src/fsd_widgets/ceremony/ui/AdminCeremonyList.tsx
  src/fsd_widgets/ceremony/ui/AdminCeremonyManagement.tsx
  src/fsd_widgets/ceremony/ui/CeremonyListItem.tsx
  src/fsd_widgets/ceremony/ui/CeremonyListWidget.tsx
  src/fsd_widgets/ceremony/ui/index.ts
  src/fsd_widgets/post/ui/PostInfoSection/PostInfoSection.tsx
  src/utils/format.ts
Labels: fix

#259 258 fix 4차 qa 수정사항
  src/app/(causw)/home/ClientGraduatePage.tsx
  src/app/(causw)/home/ClientPage.tsx
  src/fsd_entities/auth/config/academicRecordValidation.ts
  src/fsd_entities/auth/config/admissionValidation.ts
  src/fsd_entities/board/model/hooks/fetchBoardList.ts
  src/fsd_entities/user/api/delete.ts
  src/fsd_shared/ui/UseTerms.tsx
  src/fsd_widgets/auth/ui/AcademicRecordForm.tsx
  src/fsd_widgets/auth/ui/AdmissionForm.tsx
Labels: fix

#260 [FIX] 게시판 및 크자회 홈화면 아이콘 변경
  package-lock.json
  package.json
  public/homeIcons/경조사.svg
  public/homeIcons/동문수첩.svg
  public/homeIcons/크자회_공지_게시판.svg
  public/homeIcons/크자회_소통_게시판.svg
  src/app/(causw)/home/ClientGraduatePage.tsx
  src/fsd_entities/board/ui/BoardList/Board.tsx
Labels: fix

#261 QA 2차 이슈
  src/app/(causw)/board/[boardId]/BoardClientPage.tsx
  src/app/(causw)/board/[boardId]/[postId]/page.tsx
  src/app/(causw)/setting/management/attendance/detail/all/[id]/page.tsx
  src/app/(causw)/setting/management/attendance/detail/waiting/[id]/page.tsx
  src/app/(causw)/setting/management/payer/add/page.tsx
  src/app/not-found.tsx
  src/fsd_entities/banner/model/BannerEditModal.tsx
  src/fsd_entities/comment/api/delete.ts
  src/fsd_entities/comment/api/index.ts
  src/fsd_entities/comment/api/post.ts
  src/fsd_entities/comment/index.ts
  src/fsd_entities/comment/model/index.ts
  src/fsd_entities/comment/model/queries/index.ts
  src/fsd_entities/comment/model/queries/useLikeChildComment.ts
  src/fsd_entities/comment/model/queries/useLikeComment.ts
  src/fsd_entities/comment/model/queries/useToggleLikeChildComment.ts
  src/fsd_entities/comment/model/queries/useToggleLikeComment.ts
  src/fsd_entities/comment/ui/ChildCommentActionDropdown/ChildCommentActionDropdown.tsx
  src/fsd_entities/comment/ui/ChildCommentLikeButton/ChildCommentLikeButton.tsx
  src/fsd_entities/comment/ui/CommentLikeButton/CommentLikeButton.tsx
  src/fsd_entities/post/api/delete.ts
  src/fsd_entities/post/api/get.ts
  src/fsd_entities/post/api/index.ts
  src/fsd_entities/post/config/fileUploadRule.ts
  src/fsd_entities/post/index.ts
  src/fsd_entities/post/model/index.ts
  src/fsd_entities/post/model/queries/index.ts
  src/fsd_entities/post/model/queries/useGetPostDetail.ts
  src/fsd_entities/post/model/queries/useToggleLikePost.ts
  src/fsd_entities/post/model/queries/useToggleScrapPost.ts
  src/fsd_entities/post/ui/PostLikeButton/PostLikeButton.tsx
  src/fsd_entities/post/ui/PostScrapButton/PostScrapButton.tsx
  src/fsd_entities/user/config/AddPayerEntities.ts
  src/fsd_entities/user/config/AdmissionManagementDetailEntities.ts
  src/fsd_entities/user/config/CouncilFeeManagementDetailEntities.tsx
  src/fsd_entities/user/ui/ManageSettings/AdmissionManagementDetail.tsx
  src/fsd_entities/user/ui/ManageSettings/CouncilFeeManagementDetail.tsx
  src/fsd_entities/user/ui/ManageSettings/ManagementDetailInfoTable.tsx
  src/fsd_shared/@types/board.d.ts
  src/fsd_shared/@types/comment.d.ts
  src/fsd_shared/configs/constants/messages.ts
  src/fsd_shared/configs/constants/setting.ts
  src/fsd_widgets/board/ui/BoardDetail/BoardHeader.tsx
  src/fsd_widgets/comment/ui/ChildCommentCard/ChildCommentCard.tsx
  src/fsd_widgets/comment/ui/ChildCommentCardFooter/ChildCommentCardFooter.tsx
  src/fsd_widgets/comment/ui/CommentCard/CommentCard.tsx
  src/fsd_widgets/comment/ui/CommentCardButtonGroup/CommentCardButtonGroup.tsx
  src/fsd_widgets/comment/ui/CommentCardFooter/CommentCardFooter.tsx
  src/fsd_widgets/post/ui/PostActionBar/PostActionBar.tsx
  src/fsd_widgets/post/ui/PostDetailSection/PostDetailSection.tsx
  src/shared/hooks/stores/post/create/useFileUpload.ts
Labels: fix

#268 [FIX] 졸업생 전용 게시판 목록 화면 전체 불러오기
  src/fsd_entities/board/model/hooks/fetchBoardList.ts
  src/fsd_widgets/board/ui/BoardList/BoardList.tsx
  src/fsd_widgets/board/ui/BoardList/BoardListClient.tsx
Labels: fix

#271 [FIX] 설정 페이지 : toast 로딩 추가 및 더블 클릭으로 중복 생성 방지
  src/app/(causw)/ceremony/list/page.tsx
  src/app/(causw)/setting/management/payer/add/[userId]/page.tsx
  src/fsd_entities/ceremony/config/index.ts
  src/fsd_entities/ceremony/config/queryKeys.ts
  src/fsd_entities/ceremony/index.ts
  src/fsd_entities/ceremony/model/ useAdminUpdateCeremony.ts
  src/fsd_entities/ceremony/model/index.ts
  src/fsd_entities/ceremony/model/useCancelCeremony.ts
  src/fsd_entities/ceremony/model/useCeremonyCreateForm.ts
  src/fsd_entities/notification/hooks/mutations/useAddCeremonyMutation.ts
  src/fsd_entities/notification/model/useCelemonyCreateForm.ts
  src/fsd_widgets/ceremony/ui/AdminCeremonyDetail.tsx
  src/fsd_widgets/ceremony/ui/CeremonyCreateWidget.tsx
  src/fsd_widgets/ceremony/ui/CeremonyDetailPage.tsx
Labels: fix

#281 관리자 > 학적상태관리 로딩/성공 토스트 추가
  src/app/(causw)/setting/management/attendance/detail/all/[id]/page.tsx
  src/fsd_entities/user/api/put.ts
  src/fsd_entities/user/model/hooks/index.ts
  src/fsd_entities/user/model/hooks/useUpdateUserNote.ts
Labels: feat

#283 [FIX] 아이디/비밀번호 찾기 수정
  src/app/auth/signin/page.tsx
  src/fsd_entities/auth/model/hooks/useFindEmailForm.ts
  src/fsd_entities/auth/model/hooks/useFindPasswordForm.ts
  src/fsd_entities/auth/model/queries/useFindId.ts
  src/fsd_entities/auth/model/queries/useFindPassword.ts
  src/fsd_entities/auth/model/stores/useFindAccountStore.ts
  src/fsd_entities/auth/ui/AuthFormSubmitButton.tsx
  src/fsd_entities/auth/ui/AuthInput.tsx
  src/fsd_shared/@types/user.d.ts
  src/fsd_widgets/auth/ui/FindEmailForm.tsx
  src/fsd_widgets/auth/ui/FindEmailResult.tsx
  src/fsd_widgets/auth/ui/FindPasswordForm.tsx
Labels: fix

#285 [FIX] 추가 수정사항
  src/fsd_entities/post/ui/PostCard/PostCardContent.tsx
  src/fsd_entities/post/ui/PostDetailContent/PostDetailContent.tsx
  src/fsd_widgets/post/ui/PostContentSection/PostContentSection.tsx
Labels: fix

#288 [DEPLOY] 게시판 및 게시글 관련 배포 문제 해결
  src/app/(causw)/setting/page.tsx
  src/fsd_entities/post/ui/PostCard/PostCardContent.tsx
  src/fsd_entities/post/ui/PostDetailContent/PostDetailContent.tsx
  src/fsd_widgets/post/ui/PostContentSection/PostContentSection.tsx
Labels: fix

#292 설정 > 기록 메뉴 페이지들 카드 레이아웃 수정
  src/entities/board/postList/PostItemStatusBar.tsx
  src/fsd_entities/post/ui/PostCard/PostCardStatusBar.tsx
  src/fsd_entities/user/ui/PersonalSettings/MyRecordList.tsx
Labels: fix

#300 [FEAT] 안드로이드 푸시알람 설정
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/getcapacitor/myapp/ExampleInstrumentedTest.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/java/kr/co/causwv2/twa/MainActivity.java
  android/app/src/main/res/drawable-land-hdpi/splash.png
  android/app/src/main/res/drawable-land-mdpi/splash.png
  android/app/src/main/res/drawable-land-xhdpi/splash.png
  android/app/src/main/res/drawable-land-xxhdpi/splash.png
  android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  android/app/src/main/res/drawable-port-hdpi/splash.png
  android/app/src/main/res/drawable-port-mdpi/splash.png
  android/app/src/main/res/drawable-port-xhdpi/splash.png
  android/app/src/main/res/drawable-port-xxhdpi/splash.png
  android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/xml/file_paths.xml
  android/app/src/test/java/com/getcapacitor/myapp/ExampleUnitTest.java
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle.properties
  android/gradle/wrapper 2/gradle-wrapper.jar
  android/gradle/wrapper 2/gradle-wrapper.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  android/variables.gradle
  package-lock.json
  package.json
  src/fsd_entities/notification/model/.usePushNotification.ts.swp
  src/fsd_entities/notification/model/usePushNotification.ts
Labels: feat

#306 [DEPENDENCY] 안드로이드 버전3으로 업데이트
  android/app/build.gradle
Labels: dependency

#313 [FEAT] 문의하기 메뉴 추가
  package-lock.json
  src/app/(causw)/setting/page.tsx
Labels: feat
